# Generated by Django 4.1 on 2022-08-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='cc',
            field=models.PositiveIntegerField(),
        ),
    ]
