# Generated by Django 4.1 on 2022-08-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeapi', '0002_alter_bikes_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
